name: MATLAB Conversion

on:
  push:
    paths:
      - '**.mlx'

jobs:
  convert:
    runs-on: ubuntu-latest
    container:
      image: mathworks/matlab:latest
      options: --user 1001:121 --volume /tmp/license.lic:/opt/matlab/licenses/license.lic

      
    steps:
    - name: Set up MATLAB license
      run: | 
        echo "${{ secrets.MATLAB_LICENSE }}" | base64 --decode > /tmp/license.lic
    - name: Check out repository
      uses: actions/checkout@v2.4.2


    - name: Install dependencies
      run: |
        # Install any dependencies here (if needed)
    - name: Convert mlx files to PDF and HTML
      run: matlab -batch "addpath('.'); convert_files"
      
    - name: Commit and push the changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff-index --quiet HEAD || git commit -m "Add generated PDF and HTML files"
        git push

