name: MATLAB Conversion

on:
  push:
    paths:
      - '**.mlx'

jobs:
  convert:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2.4.2

      - name: Install dependencies
        run: |
          # Install any dependencies here (if needed)

      - name: Convert mlx files to PDF and HTML
        shell: bash
        run: |
          matlab -batch "addpath('.'); convert_files"
      
      - name: Commit and push the changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "Add generated PDF and HTML files"
          git push
