name: MATLAB Conversion

on:
  push:
    paths:
      - '**.mlx'

jobs:
  convert:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2.4.2

      - name: Convert mlx files to PDF and HTML
        run: |
          echo "Current working directory: $(Get-Location)"
          echo "Location of convert_files.m: $(Get-Location)\convert_files.m"
          matlab -batch "addpath('.'); convert_files"

      - name: Commit and push the changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "Add generated PDF and HTML files"
          git push

